import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    const val adapters: String = "com.android.databinding:adapters:" + Versions.adapters

    /**
     * [android-maven-gradle-plugin website](https://github.com/dcendents/android-maven-gradle-plugin) */
    const val android_maven_gradle_plugin: String =
            "com.github.dcendents:android-maven-gradle-plugin:" + Versions.android_maven_gradle_plugin

    /**
     * [appcompat-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    /**
     * [auto-value website](https://github.com/google/auto) */
    const val auto_value: String = "com.google.auto.value:auto-value:" + Versions.auto_value

    const val auto_value_annotations: String =
            "com.jakewharton.auto.value:auto-value-annotations:" + Versions.auto_value_annotations

    /**
     * [auto-value-parcel website](https://github.com/rharter/auto-value-parcel/) */
    const val auto_value_parcel: String =
            "com.ryanharter.auto.value:auto-value-parcel:" + Versions.auto_value_parcel

    /**
     * [baseLibrary website](https://developer.android.com/studio) */
    const val baselibrary: String = "com.android.databinding:baseLibrary:" + Versions.baselibrary

    /**
     * [databinding-compiler website](https://developer.android.com/studio) */
    const val databinding_compiler: String =
            "androidx.databinding:databinding-compiler:" + Versions.databinding_compiler

    const val epublib_core: String =
            "com.github.timfreiheit.epublib:epublib-core:" + Versions.epublib_core

    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String =
            "com.android.support.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val gradle: String = "com.android.tools.build:gradle:" + Versions.gradle

    const val gradle_kotlin_dsl_libs: String =
            "jmfayard.github.io:gradle-kotlin-dsl-libs:" + Versions.gradle_kotlin_dsl_libs

    /**
     * [gson website](https://github.com/google/gson) */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.kotlin_annotation_processing_gradle

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.kotlin_gradle_plugin

    /**
     * [kotlin-stdlib-jdk7 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" + Versions.kotlin_stdlib_jdk7

    const val library: String = "com.android.databinding:library:" + Versions.library

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * [recyclerview-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val recyclerview_v7: String =
            "com.android.support:recyclerview-v7:" + Versions.recyclerview_v7

    /**
     * [rxandroid website](https://github.com/ReactiveX/RxAndroid) */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * [rxjava website](https://github.com/ReactiveX/RxJava) */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * [stetho website](https://github.com/facebook/stetho) */
    const val stetho: String = "com.facebook.stetho:stetho:" + Versions.stetho

    const val verticalseekbar: String =
            "com.h6ah4i.android.widget.verticalseekbar:verticalseekbar:" + Versions.verticalseekbar

    object Versions {
        const val aapt2: String = "3.2.0-4818971" // available: milestone=3.3.0-alpha13-5013011

        const val adapters: String = "3.2.0" // available: milestone=3.3.0-alpha13

        const val android_maven_gradle_plugin: String = "2.0" // available: milestone=2.1

        const val appcompat_v7: String = "25.2.0" // available: milestone=28.0.0

        const val auto_value: String = "1.5" // available: milestone=1.6.3rc1

        const val auto_value_annotations: String = "1.5" // up-to-date

        const val auto_value_parcel: String = "0.2.5" // available: milestone=0.2.6

        const val baselibrary: String = "3.2.0" // available: milestone=3.3.0-alpha13

        const val databinding_compiler: String = "3.2.0" // available: milestone=3.3.0-alpha13

        const val epublib_core: String = "645ea52ef8" 
                /* error: Could not find any matches for com.github.timfreiheit.epublib:epublib-core:+ as no versions of com.github.timfreiheit.epublib:epublib-core are available.
                Searched in the following locations:
                  - file:/Users/jmfayard/Dev/android-sdk-macosx/extras/m2repository/com/github/timfreiheit/epublib/epublib-core/maven-metadata.xml
                  - file:/Users/jmfayard/Dev/android-sdk-macosx/extras/m2repository/com/github/timfreiheit/epublib/epublib-core/ 
                .... */

        const val espresso_core: String = "2.2.2" // available: milestone=3.0.2

        const val gradle: String = "3.2.0" // available: milestone=3.3.0-alpha13

        const val gradle_kotlin_dsl_libs: String = "0.2.1" // up-to-date

        const val gson: String = "2.8.2" // available: milestone=2.8.5

        const val junit: String = "4.12" // up-to-date

        const val kotlin_annotation_processing_gradle: String = "1.2.71" // up-to-date

        const val kotlin_gradle_plugin: String = "1.2.71" // up-to-date

        const val kotlin_stdlib_jdk7: String = "1.2.71" // up-to-date

        const val library: String = "3.2.0" // available: milestone=3.3.0-alpha13

        const val lint_gradle: String = "26.2.0" // available: milestone=26.3.0-alpha13

        const val recyclerview_v7: String = "25.2.0" // available: milestone=28.0.0

        const val rxandroid: String = "2.0.1" // available: milestone=2.1.0

        const val rxjava: String = "2.1.6" // available: milestone=2.2.2

        const val stetho: String = "1.4.2" // available: milestone=1.5.0

        const val verticalseekbar: String = "0.7.1" // available: milestone=1.0.0
    }

    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.0-20181002235907+0000"

        const val releaseCandidate: String = ""
    }
}
